#library "TRACKER"
#include "zcommon.acs"
#include "AACS.acs"
#import "QCDE.bcs"

//=============================================================================
//=============================================================================
//=============================================================================
//
//
//		PLAYER LIFECYCLE RELATED SCRIPTS
//
//
//=============================================================================
//=============================================================================
//=============================================================================


//=============================================================================
//
//		Event Handlers
//
//=============================================================================

bool DMgame = false;
int maxScore;

Script "QCDE_Open" Open
{
	// Any setup to the whole map, separate from players, goes here.
	
	// Auto taunting setup
	if(!taunt_chance) taunt_chance = 100;
	if(taunt_chance > 500) taunt_chance = 500;
	taunt_chance += 20;
	
	// Translations
	CreateTranslation(TRANSLATION_REDTEAM,  112:127=168:191, 144:159=168:191); // Red
	CreateTranslation(TRANSLATION_BLUETEAM, 112:127=192:207, 144:159=192:207); // Blue
	
	CreateTranslation(TRANSLATION_GCOLOR,   0:255=[ 90, 50,130]:[ 90, 50,130]); // Gauntlet purple
	CreateTranslation(TRANSLATION_MGCOLOR,  0:255=[255,255, 50]:[255,255, 50]); // Bullet yellow
	CreateTranslation(TRANSLATION_HMGCOLOR, 0:255=[255,255, 50]:[255,255, 50]); // ^
	CreateTranslation(TRANSLATION_SGCOLOR,  0:255=[255,140,  0]:[255,140,  0]); // Shell orange
	CreateTranslation(TRANSLATION_SSGCOLOR, 0:255=[255,140,  0]:[255,140,  0]); // ^
	CreateTranslation(TRANSLATION_NGCOLOR,  0:255=[  0, 70,255]:[  0, 70,255]); // Nail blue
	CreateTranslation(TRANSLATION_SNGCOLOR, 0:255=[  0, 70,255]:[  0, 70,255]); // ^
	CreateTranslation(TRANSLATION_TBCOLOR,  0:255=[130,225, 20]:[130,255, 20]); // Bolt lime
	CreateTranslation(TRANSLATION_RLCOLOR,  0:255=[255, 20,  0]:[255, 20,  0]); // Rocket red
	CreateTranslation(TRANSLATION_LGCOLOR,  0:255=[  0,255,255]:[  0,255,255]); // Coil cyan
	CreateTranslation(TRANSLATION_RGCOLOR,  0:255=[ 30,255, 30]:[ 30,255, 30]); // Rail green
	CreateTranslation(TRANSLATION_BFGCOLOR, 0:255=[220, 20,255]:[220, 20,255]); // BFG violet
	
	CreateTranslation(TRANSLATION_HUNTERTRACE,     0:255=[255, 64, 64]:[16,16,16]); // Red
	CreateTranslation(TRANSLATION_HUNTERTRACEBLUE, 0:255=[ 64, 96,255]:[16,16,16]); // Blue
	
	ACS("QCDE_Gamemode");
	ACS("QCDE_QcsInterpreter");
	
	ACS_NamedExecuteAlways("QCDE_DamageScalarWarning",0);
	
	// This script is called Always (on the next, 1st tic) to allow 0th tic
	// to set up dynamic themes.
	ACS_NamedExecuteAlways("QCDE_ThemeSetup",0);
	
	delay(1);
	
	ACS_NamedExecuteAlways("QCDE_RareTracker",0);
}

Script "QCDE_Enter" Enter
{
	// Vanilla rules on titlemap, no QCDE extensions
	if(GameType() == GAME_TITLE_MAP) terminate;
	
	// Spectators: Please don't
	if(PlayerIsSpectator(PlayerNumber())) terminate;

	ACS_NamedExecuteAlways("QCDE_Enter_Flash", 0);

	// Any setup separate from a living player should be performed here.
	if(GameType() >= GAME_NET_DEATHMATCH) DMgame = true;
	
	if(!DMgame && CheckInventory("Body_Big") && !CheckInventory("TankAlreadyWarned")) 
	{
		GiveInventory("TankAlreadyWarned",1);
		ACS_NamedExecuteAlways("QCDE_CoopTankWarning",0);
	}
	
	// If started opening lootbox on last map, restore ability to open
	TakeInventory("OpeningLootbox",1);
	
	// And then, as last step, setup for an existing player actor is called.
	ACS_NamedExecuteAlways("QCDE_NewLife",0,true);
	ACS_NamedExecuteAlways("QCDE_NewLife_BOT",0);
}

Script "QCDE_Enter_Flash" clientside
{
	//Fade in applied when player enters map, not called through any other script.
	Fadeto (0, 0, 0, 1.0, 0);
	SetFont("BIGFONT");
	HudMessage(s:"\c[brite]Loading..."; HUDMSG_PLAIN, HMID_LOADING, -1, 0.5,0.4, 0.02);
	Fadeto (0, 0, 0, 0  , 0.3);
	delay(1);
	HudMessage(s:""; HUDMSG_PLAIN, HMID_LOADING, -1, 0.5,0.4, 0.01); // done loading
}

Script "QCDE_Respawn" Respawn
{
	// Spectators: Please don't
	if(PlayerIsSpectator(PlayerNumber())) terminate;
	
	ACS_NamedExecuteAlways("QCDE_NewLife",0,false);
	ACS_NamedExecuteAlways("QCDE_NewLife_BOT",0);
}

Script "QCDE_Return" Return
{
	// Spectators: Please don't
	if(PlayerIsSpectator(PlayerNumber())) terminate;
	
	ACS_NamedExecuteAlways("QCDE_NewLife",0);
	ACS_NamedExecuteAlways("QCDE_NewLife_BOT",0);
}

// This script is responsible for most effects that concern player.
// It is executed both on first birth and on every consequent.
Script "QCDE_NewLife" (int firsttime)
{
	if(!-~PlayerNumber()) terminate; // <-- fixes "addbot; removebot" bug
	
	Thing_ChangeTID(1000 + PlayerNumber(), 0); // free player TID from other corpses
	Thing_ChangeTID(0, 1000 + PlayerNumber()); // set player TID
	TakeInventory("ImDead",999); //removes "death" token indicator
	TakeInventory("NoAbilitiesToken",999); // allows casting again
	
	// vital first step: ensure class token and stack caps correctness
	ACS("QCDE_ResetClass", firsttime);
	
	ACS("QCDE_UpdateScores_CLIENTSIDE");
	ACS_NamedExecuteAlways("QCDE_DM_HealthAndWeapons"	,0);
	ACS_NamedExecuteAlways("QCDE_DM_AmmoCapacity"		,0);
	ACS_NamedExecuteAlways("QCDE_DM_PlayerCollision"	,0);
	ACS_NamedExecuteAlways("QCDE_PlayerSpeed"			,0);
	ACS_NamedExecuteAlways("QCDE_Degeneration"			,0);
	ACS_NamedExecuteAlways("QCDE_PassiveAbility"		,0);
	ACS_NamedExecuteAlways("QCDE_StartingArmor"			,0);
	ACS_NamedExecuteAlways("QCDE_UpdateTotemCount"		,0);
	ACS_NamedExecuteAlways("QCDE_UpdateLives"			,0);
	ACS_NamedExecuteAlways("QCDE_GiveDelayed"			,0);
	ACS_NamedExecuteAlways("QCDE_InitLCG"				,0);
	ACS_NamedExecuteAlways("QCDE_RegiveKeys"			,0);
	ACS_NamedExecuteAlways("QCDE_InitLMS"				,0);
	ACS_NamedExecuteAlways("QCDE_TrackLowAmmo_CLIENT"	,0);
	ACS_NamedExecuteAlways("QCDE_TrackLowHealth_CLIENT"	,0);
	ACS_NamedExecuteAlways("QCDE_AbilityCooldown"		,0, -1); // continue cooldowns from last map
	ACS_NamedExecuteAlways("QCDE_UpdateMultiusePeriod"	,0);
	ACS_NamedExecuteAlways("QCDE_StartingWeapon_Apply"	,0);
	ACS_NamedExecuteAlways("QCDE_CleanUpAbilities"		,0);	//to clean up flag/token changes that occurred in the previous level
	ACS_NamedExecuteAlways("QCDE_AllyMarker_CLIENT"		,0, true);
	ACS_NamedExecuteAlways("QCDE_StoreTeam"				,0);
	ACS_NamedExecuteAlways("QCDE_BindAbilityKey_Hint"	,0);
	
	if(firsttime) ACS_NamedExecuteAlways("QCDE_FreeTribolt",0);
	
	rereadCvars();
	//if(!CheckInventory("Starter_CantChoose")) {
	//	ACS_NamedExecuteAlways("QCDE_StartingWeapon_Hint"	,0);
	//}
	
	bool teamplay  = getCvar("teamplay");
	bool teamlms   = getCvar("teamlms");
	bool pointgame = getCvar("teampossession") || getCvar("domination") || getCvar("skulltag");
	bool ctf       = getCvar("ctf") || getCvar("oneflagctf");
	bool duel      = getCvar("duel");
	bool instagib  = getCvar("instagib");
	bool rockarena = getCvar("rocketarena");
	if(teamplay || teamlms || pointgame || ctf) {
		GiveInventory("TeamDeathmatch", 1);
		if(teamlms)   { maxScore = getCvar(  "winlimit"); if(!maxScore) maxScore =  10; }
		if(teamplay)  { maxScore = getCvar( "fraglimit"); if(!maxScore) maxScore = 100; }
		if(pointgame) { maxScore = getCvar("pointlimit"); if(!maxScore) maxScore = 100; }
		if(ctf)       { maxScore = getCvar("pointlimit"); if(!maxScore) maxScore =  10; }
	}
	else // ffa or duel
	{
		if(duel) GiveInventory("Duel", 1);
		
		maxScore = getCvar("fraglimit");
		if(!maxScore) 
			if(!duel)
				maxScore = 100;
			else
				maxScore = 20;
	}
	if(instagib)  GiveInventory("Instagib",1);
	if(rockarena) GiveInventory("RocketArena",1);
	
	ACS_NamedExecuteAlways("Footstep_Initialize",0,0,0,0);
	
	// After all setup is done, we can launch the loops.
	ACS_NamedExecuteAlways("QCDE_Tracker"				,0);
	ACS_NamedExecuteAlways("QCDE_Tracker_CLIENTSIDE"	,0);
}

Script "QCDE_Death" Death
{
	//Generalized effects for all modes
	GiveInventory("ImDead",1);					//Gives token for A_Warpers
	TakeInventory("MurderToken",1000);			//Eradicator loses a lot of juice, 
	TakeInventory("MurderLevel",5);				//but not all of it
	SetPlayerProperty(0,0,PROP_TOTALLYFROZEN);	//Unfreezes to be able to respawn
	StopSound(5);								//stops any looping sounds
	if(CheckInventory("Class_Kane")) {StopSound(CHAN_BODY);} //force stops crouchslide sound
	
	ACS_NamedExecuteAlways("QCDE_DM_FragBeep"		,0);
	ACS_NamedExecuteAlways("QCDE_DM_InitPowerups"	,0);
	ACS_NamedExecuteAlways("QCDE_DM_DropPowerups"	,0);
	ACS_NamedExecuteAlways("QCDE_DM_HurtDave"		,0);
	ACS_NamedExecuteAlways("QCDE_DropUpgrades"		,0);
	ACS_NamedExecuteAlways("QCDE_Target_Taunt"		,0,10);
	ACS("QCDE_UpdateScores_CLIENTSIDE",true);
	ACS("QCDE_DM_DropEldersSoul");
	ACS("QCDE_EldersSoul_RewardSoulCarrier");
	
	if(!IsKillerEligibleForKillBonus()) terminate;
	
	str scrypt = strparam(s:"QCDE_PlayerKill_", s:GetActorClass(GetActorProperty(0, APROP_TargetTID)));
	ACS(scrypt);
}

Script "QCDE_Disconnect" (int gone) Disconnect
{
	ACS("QCDE_UpdateScores_CLIENTSIDE");
}

//=============================================================================
//
//		Tracker Loops
//
//=============================================================================

int MAXIMUM_TAP_DELAY = 35;
int INQUISITOR_THRUST = 11;
int MOVEMENT_BUTTONS = (BT_MOVELEFT|BT_FORWARD|BT_MOVERIGHT|BT_BACK);

Script "QCDE_Tracker" (void)
{
	int buttons, oldbuttons, triggers;
	int lastTapTime, lastTapValue, angle;
	int plr = PlayerNumber();
	while(GetActorProperty(0,APROP_HEALTH) > 0)
	{
		// Player input information
		oldbuttons = buttons;
		buttons = GetPlayerInput(plr, MODINPUT_BUTTONS);
		int ws_axis = GetPlayerInput(plr, INPUT_FORWARDMOVE);
		int ad_axis = GetPlayerInput(plr, INPUT_SIDEMOVE);
		if(ws_axis < 0) buttons |= BT_BACK;
		if(ws_axis > 0) buttons |= BT_FORWARD;
		if(ad_axis < 0) buttons |= BT_MOVELEFT;
		if(ad_axis > 0) buttons |= BT_MOVERIGHT;
		triggers = buttons & ~oldbuttons;
		
		// Health/armor and multiplayer score display
		updateHealthArmorDisplay();
		if(GameType() >= GAME_NET_DEATHMATCH)
		{
			int tscore1, tscore2;
			if(CheckInventory("Duel"))
			{
				tscore1 = PlayerFrags();
				tscore2 = ACS("QCDE_OtherPlayerFrags");
				if(tscore1 > maxScore) maxScore = tscore1;
				if(tscore2 > maxScore) maxScore = tscore2;
				SetInventory("Team1Score", tscore1 * 220 / maxScore);
				SetInventory("Team2Score", tscore2 * 220 / maxScore);
			}
			else if(!CheckInventory("TeamDeathmatch"))
			{
				tscore1 = PlayerFrags();
				if(tscore1 > maxScore) maxScore = tscore1;
				SetInventory("Team1Score", tscore1 * 220 / maxScore);
			}
		}
		
		// Choose weapon
		if(buttons & MOVEMENT_BUTTONS)
		{
			if(CheckInventory("Starter_ChooseNow"))
			{
				if (buttons & BT_MOVELEFT) { 
					GiveInventory("Starter_Machinegun",1);
					TakeInventory("Starter_Shotgun"   ,1);
					TakeInventory("Starter_Nailgun"   ,1);
					SetCvar("cl_startingWeapon", 1);
					ACS_NamedExecuteAlways("QCDE_StartingWeapon_Hint_Success",0,1);
					ACS_NamedExecuteAlways("QCDE_StartingWeapon_Apply",0);
				} 
				if (DMgame && (buttons & BT_FORWARD)) {
					TakeInventory("Starter_Machinegun",1);
					GiveInventory("Starter_Shotgun"   ,1);
					TakeInventory("Starter_Nailgun"   ,1);
					SetCvar("cl_startingWeapon", 2);
					ACS_NamedExecuteAlways("QCDE_StartingWeapon_Hint_Success",0,2);
					ACS_NamedExecuteAlways("QCDE_StartingWeapon_Apply",0);
				} 
				if (buttons & BT_MOVERIGHT) { 
					TakeInventory("Starter_Machinegun",1);
					TakeInventory("Starter_Shotgun"   ,1);
					GiveInventory("Starter_Nailgun"   ,1);
					SetCvar("cl_startingWeapon", 3);
					ACS_NamedExecuteAlways("QCDE_StartingWeapon_Hint_Success",0,3);
					ACS_NamedExecuteAlways("QCDE_StartingWeapon_Apply",0);
				}
				delay(1);
			}
			// As soon as player moves, with menu or without, chance is gone.
			SetInventory("Starter_ChooseNow", false);
			if(!CheckInventory("Starter_CantChoose"))
				ACS_NamedExecuteAlways("QCDE_StartingWeapon_Hint_Stop",0);
			SetInventory("Starter_CantChoose", true);
		}
		
		if(!(Timer() % 19)) // once every 19 tics
			ACS_NamedExecuteAlways("QCDE_MapProgressChecker",0);
		
		// Book-keeping on powerup duration
		if(!(Timer() % 7)) // once every 7 tics
			ACS_NamedExecuteAlways("QCDE_TokenizePowerups",0);
		
		// Feedback settings
		if(!(Timer() % 50))
		{
			rereadCvars();
		}
		
		delay(1);
	}
	
	// Setting all of the tokens affected in the loop to end-of-life values
	SetInventory("CurrentHealthToken", 0);
	SetInventory("CurrentHealthBar",   0);
	SetInventory("CurrentArmorToken",  0);
	SetInventory("CurrentArmorBar",    0);
	SetInventory("SuperHealthToken",   0);
	SetInventory("SuperHealthBar",     0);
	SetInventory("SuperArmorToken",    0);
	SetInventory("SuperArmorBar",      0);
	SetInventory("Starter_CantChoose", 0);
	
	// Remove ally marker
	Thing_Remove(MARKER_TIDBASE + plr);
	
	// Give away `resurrect` cheat
	while(GameType() == GAME_SINGLE_PLAYER  &&  plr > -1)
	{
		if(GetActorProperty(0,APROP_HEALTH) > 0)
		{
			GiveInventory("Resurrected",1);
			terminate;
		}
		delay(35);
	}
}

function void updateHealthArmorDisplay(void)
{
	int hp = GetActorProperty(0,APROP_HEALTH);
	int maxHP = CheckInventory("MaxHealthToken");
	int overHP = hp;
	if(hp > maxHP) hp = maxHP;
	int maxHP_scaled = maxHP, hp_scaled = hp, overHP_scaled = overHP;
	int greater = maxHP; if(overHP > greater) greater = overHP;
	SetInventory("CurrentHealthToken",   hp);
	SetInventory("SuperHealthToken", overHP);
	SetInventory("FlatHealthToken", greater >= 300);
	if(greater >= 300)
	{
		int scale_to = 200 + sqrt(greater * 4);
		if(scale_to > 350) scale_to = 350;
		 maxHP_scaled =  maxHP_scaled * scale_to / greater;
		    hp_scaled =     hp_scaled * scale_to / greater;
		overHP_scaled = overHP_scaled * scale_to / greater;
	}
	SetInventory("MaxHealthBar",    maxHP_scaled);
	SetInventory("CurrentHealthBar",   hp_scaled);
	SetInventory("SuperHealthBar", overHP_scaled);
	

	
	int ap = CheckInventory("BasicArmor");
	int maxAP = CheckInventory("MaxArmorToken");
	int overAP = ap;
	if(ap > maxAP) ap = maxAP;
	int maxAP_scaled = maxAP, ap_scaled = ap, overAP_scaled = overAP;
	greater = maxAP; if(overAP > greater) greater = overAP;
	SetInventory("CurrentArmorToken",   ap);
	SetInventory("SuperArmorToken", overAP);
	SetInventory("FlatArmorToken", greater >= 300);
	if(greater >= 300)
	{
		scale_to = 200 + sqrt(greater * 4);
		if(scale_to > 350) scale_to = 350;
		 maxAP_scaled =  maxAP_scaled * scale_to / greater;
		    Ap_scaled =     Ap_scaled * scale_to / greater;
		overAP_scaled = overAP_scaled * scale_to / greater;
	}
	SetInventory("MaxArmorBar",    maxAP_scaled);
	SetInventory("CurrentArmorBar",   Ap_scaled);
	SetInventory("SuperArmorBar", overAP_scaled);
}

function void rereadCvars(void)
{
	SetInventory("NoWeaponBar",      !GetCVar("cl_showWeaponBar"  ));
	SetInventory("Speedometer",       GetCVar("cl_speedometer"    ));
	SetInventory("PlayHitBeep",       GetCVar("cl_hitbeep"        ));
	SetInventory("PlayHitMark",       GetCVar("cl_hitmarker"      ));
	SetInventory("WepNoRecoilToken", !GetCVar("cl_weaponrecoil"   ));
	SetInventory("WepNoFlashToken",  !GetCVar("cl_weaponfireflash"));
	SetInventory("AutoTauntToken",    GetCVar("cl_autoTaunt"      ));
	SetInventory("LGTransparency",    GetCVar("cl_lgtransparency" ));
	SetInventory("FlatHealthPref",    GetCVar("cl_barStyle"       ));
	SetInventory("FlatArmorPref",     GetCVar("cl_barStyle"       ));
}

Script "QCDE_OtherPlayerFrags" (void)
{
	SetResultValue(-1);
	int me = PlayerNumber();
	int i;
	for(i = 0; i < 64; i++)
	{
		SetActivator(1000 + i);
		if(me == PlayerNumber()) continue;
		if(PlayerInGame(PlayerNumber())) 
		{
			SetResultValue(PlayerFrags());
			terminate;
		}
	}
}

Script "QCDE_PlayerFrags" (int plr)
{
	SetActivator(1000 + plr);
	SetResultValue(PlayerFrags());
}

Script "QCDE_RareTracker" (void)
{
	while(true)
	{
		if (GameType() == GAME_NET_DEATHMATCH  &&  PlayerCount() > 2  &&  GetCvar("sv_crowntheleader"))
		{
			ACS("QCDE_CrownTheBest");
		}
		
		delay(35);
	}
}

int carriers[NUMBER_OF_TEAMS];

Script "QCDE_Tracker_CLIENTSIDE" (void) clientside
{
	if(PlayerNumber() != ConsolePlayerNumber()) terminate;
	
	int lastSpeed, speed;
	int ctf = getCvar("ctf") || getCvar("oneflagctf");
	int myTeam = GetPlayerInfo(PlayerNumber(), PLAYERINFO_TEAM);
	int scoresum, scoresum_was, our_uncarried, their_uncarried, i;
	for(i = 0; i < NUMBER_OF_TEAMS; i++) carriers[i] = -1;
	
	while(GetActorProperty(0,APROP_HEALTH) > 0)
	{
		// CTF sounds
		
		if(ctf)
		{
			our_uncarried = false;
			their_uncarried = false;
			scoresum = 0;
			for(i = 0; i < NUMBER_OF_TEAMS; i++)
			{
				int car   = GetTeamProperty(i, TPROP_Carrier);
				scoresum += GetTeamProperty(i, TPROP_Score);
				
				// change of flag carrier
				if(car != carriers[i] && Timer() > 35)
				{
					if(i == myTeam)	// my flag
					{
						if(carriers[i] == -1) AmbientSound("Map/CTF/FlagCaptureHostile", 127); // was taken?
						else our_uncarried = true; // was dropped, OR completely captured
					}
					else // enemy flag
					{
						if(carriers[i] == -1) AmbientSound("Map/CTF/FlagCaptureFriendly", 127); // was taken?
						else their_uncarried = true; // was dropped, OR completely captured
					}
					
					carriers [i] = car;
				}
			}
			
			if(scoresum_was != scoresum) // somebody scored!
			{
				if(our_uncarried)        AmbientSound("Map/CTF/FlagDeliverHostile",  127); // our flag was used
				else if(their_uncarried) AmbientSound("Map/CTF/FlagDeliverFriendly", 127); // their flag was used
				
				scoresum_was = scoresum;
			}
			else if(our_uncarried)   AmbientSound("Map/CTF/FlagSpawn", 127); // our flag was dropped
			else if(their_uncarried) AmbientSound("Map/CTF/FlagReset", 127); // their flag was dropped
		}
		
		delay(1);
	}
}


//=============================================================================
//
//		Bot enhancement
//
//=============================================================================

// This script sets up everything needed for a bot.
// Like its non-bot counterpart, it is executed both on birth and respawn.
#define BOT_INITIAL_THRUST 20
Script "QCDE_NewLife_BOT" (void)
{
	if(!PlayerIsBot(PlayerNumber())) terminate;
	if(GameType() < GAME_NET_DEATHMATCH) terminate; // bots only matter in DM
	
	// Don't include scripts that apply to both live players and bots.
	ACS_NamedExecuteAlways("QCDE_Bot_Weaponize",0);
	
	// Initial thrust, to prevent them from camping spawn
	ThrustThing(GetActorAngle(0) >> 8, BOT_INITIAL_THRUST, 0, 0);
	ThrustThingZ(0, BOT_INITIAL_THRUST, 0, 1);
	
	// After all setup is done, we can launch the loops.
	ACS_NamedExecuteAlways("QCDE_Tracker_BOT",0);
	ACS_NamedExecuteAlways("QCDE_AbilityTracker_BOT",0); // Separate for greater update rate
}

Script "QCDE_Tracker_BOT" (void)
{
	while(GetActorProperty(0,APROP_HEALTH) > 0)
	{
		ACS_NamedExecuteAlways("QCDE_Bot_SelectWeapon"     , 0);
		ACS_NamedExecuteAlways("QCDE_Bot_Twitch"           , 0);
		ACS_NamedExecuteAlways("QCDE_Bot_FreezetagTimeout" , 0);
		
		delay(random(8,25));
		
		ACS_NamedExecuteAlways("QCDE_Bot_Twitch", 0);
		ACS_NamedExecuteAlways("QCDE_VoiceLine" , 0, 2, 0, Timer()); // 2% chance to taunt every sec
		
		delay(random(8,25));
		
		ACS_NamedExecuteAlways("QCDE_Bot_Twitch", 0);
		ACS_NamedExecuteAlways("QCDE_Bot_Buff"  , 0);
		
		delay(random(8,25));
	}
	
	// Setting all of the tokens affected in the loop to end-of-life values
	
}


//=============================================================================
//
//		Low Ammo Warning
//
//=============================================================================

#define LOW_AMMO 50

script "QCDE_TrackLowAmmo_CLIENT" (void) CLIENTSIDE
{
	if(PlayerNumber() - ConsolePlayerNumber()) terminate; // Only for myself
	
	bool warned, noammo;
	while(GetActorProperty(0, APROP_Health) > 0)
	{
		delay(3);
		
		// Console toggle
		if(!GetCvar("cl_lowAmmoWarning"))
		{
			delay(70);
			continue;
		}
		
		noammo = false;
		// Ammo count
		if (((CheckWeapon("QCMachinegun") || CheckWeapon("QCHeavyMachinegun") || CheckWeapon("QCMachinegunDM") || CheckWeapon("QCHeavyMachinegunDM")) && (CheckInventory("QCBulletAmmo") <= 50) && (warned != 2)) ||
			((CheckWeapon("QCShotgun")    || CheckWeapon("QCSuperShotgun")    || CheckWeapon("QCShotgunDM")    || CheckWeapon("QCSuperShotgunDM")   ) && (CheckInventory("QCShellAmmo")  <= 10) && (warned != 3)) ||
			((CheckWeapon("QCNailgun")    || CheckWeapon("QCSuperNailgun")    || CheckWeapon("QCNailgunDM")    || CheckWeapon("QCSuperNailgunDM")   ) && (CheckInventory("QCNailAmmo")   <= 50) && (warned != 4)) ||
			((CheckWeapon("QCTribolt")                                        || CheckWeapon("QCTriboltDM")                                         ) && (CheckInventory("QCBoltAmmo")   <= 10) && (warned != 1)) ||
			((CheckWeapon("QCRocketLauncher")                                 || CheckWeapon("QCRocketLauncherDM")                                  ) && (CheckInventory("QCRocketAmmo") <= 10) && (warned != 5)) ||
			((CheckWeapon("QCLightningGun")                                   || CheckWeapon("QCLightningGunDM")                                    ) && (CheckInventory("QCCoilAmmo")   <= 10) && (warned != 6)) ||
			((CheckWeapon("QCRailgun")                                        || CheckWeapon("QCRailgunDM")                                         ) && (CheckInventory("QCSlugAmmo")   <=  5) && (warned != 7)) ||
			((CheckWeapon("QCBFG")                                            || CheckWeapon("QCBFGDM")                                             ) && (CheckInventory("QCBFGAmmo")    <=  0) && (warned != 8)))
		{
			if((CheckWeapon("QCMachinegun") || CheckWeapon("QCHeavyMachinegun") || CheckWeapon("QCMachinegunDM") || CheckWeapon("QCHeavyMachinegunDM")) && (!CheckInventory("QCBulletAmmo"))) noammo = true;
			if((CheckWeapon("QCShotgun")    || CheckWeapon("QCSuperShotgun")    || CheckWeapon("QCShotgunDM")    || CheckWeapon("QCSuperShotgunDM")   ) && (!CheckInventory("QCShellAmmo") )) noammo = true;
			if((CheckWeapon("QCNailgun")    || CheckWeapon("QCSuperNailgun")    || CheckWeapon("QCNailgunDM")    || CheckWeapon("QCSuperNailgunDM")   ) && (!CheckInventory("QCNailAmmo")  )) noammo = true;
			if((CheckWeapon("QCTribolt")                                        || CheckWeapon("QCTriboltDM")                                         ) && (!CheckInventory("QCBoltAmmo")  )) noammo = true;
			if((CheckWeapon("QCRocketLauncher")                                 || CheckWeapon("QCRocketLauncherDM")                                  ) && (!CheckInventory("QCRocketAmmo"))) noammo = true;
			if((CheckWeapon("QCLightningGun")                                   || CheckWeapon("QCLightningGunDM")                                    ) && (!CheckInventory("QCCoilAmmo")  )) noammo = true;
			if((CheckWeapon("QCRailgun")                                        || CheckWeapon("QCRailgunDM")                                         ) && (!CheckInventory("QCSlugAmmo")  )) noammo = true;
			if((CheckWeapon("QCBFG")                                            || CheckWeapon("QCBFGDM")                                             ) && (!CheckInventory("QCBFGAmmo")   )) noammo = true;
			
			ACS_NamedExecuteAlways("QCDE_LowAmmoAlert_CLIENT",0, true, GetCvar("cl_lowAmmoWarning") > 1, noammo);
			if(CheckWeapon("QCMachinegun") || CheckWeapon("QCHeavyMachinegun") || CheckWeapon("QCMachinegunDM") || CheckWeapon("QCHeavyMachinegunDM")) warned = 2;
			if(CheckWeapon("QCShotgun")    || CheckWeapon("QCSuperShotgun")    || CheckWeapon("QCShotgunDM")    || CheckWeapon("QCSuperShotgunDM")   ) warned = 3;
			if(CheckWeapon("QCNailgun")    || CheckWeapon("QCSuperNailgun")    || CheckWeapon("QCNailgunDM")    || CheckWeapon("QCSuperNailgunDM")   ) warned = 4;
			if(CheckWeapon("QCTribolt")                                        || CheckWeapon("QCTriboltDM")                                         ) warned = 1;
			if(CheckWeapon("QCRocketLauncher")                                 || CheckWeapon("QCRocketLauncherDM")                                  ) warned = 5;
			if(CheckWeapon("QCLightningGun")                                   || CheckWeapon("QCLightningGunDM")                                    ) warned = 6;
			if(CheckWeapon("QCRailgun")                                        || CheckWeapon("QCRailgunDM")                                         ) warned = 7;
			if(CheckWeapon("QCBFG")                                            || CheckWeapon("QCBFGDM")                                             ) warned = 8;
			///* debug */ log(s:"\c[bludi]Alerting about low ammo! Text: ", d:GetCvar("cl_lowAmmoWarning") > 1, s:", stays: ", d:GetCvar("cl_lowAmmoWarning") >= 3);
			str weapon = GetWeapon();
			
			if(GetCvar("cl_lowAmmoWarning") >= 3) 
			while(!stricmp(weapon, GetWeapon()))
			{
				delay(3);
				ACS_NamedExecuteAlways("QCDE_LowAmmoAlert_CLIENT",0, false, true, noammo);
				if((!stricmp(weapon,"QCMachinegun") || !stricmp(weapon,"QCHeavyMachinegun") || !stricmp(weapon,"QCMachinegunDM") || !stricmp(weapon,"QCHeavyMachinegunDM")) && (CheckInventory("QCBulletAmmo") > 50)) break;
				if((!stricmp(weapon,"QCShotgun")    || !stricmp(weapon,"QCSuperShotgun")    || !stricmp(weapon,"QCShotgunDM")    || !stricmp(weapon,"QCSuperShotgunDM")   ) && (CheckInventory("QCShellAmmo")  > 10)) break;
				if((!stricmp(weapon,"QCNailgun")    || !stricmp(weapon,"QCSuperNailgun")    || !stricmp(weapon,"QCNailgunDM")    || !stricmp(weapon,"QCSuperNailgunDM")   ) && (CheckInventory("QCNailAmmo")   > 50)) break;
				if((!stricmp(weapon,"QCTribolt")                                            || !stricmp(weapon,"QCTriboltDM")                                             ) && (CheckInventory("QCBoltAmmo")   > 10)) break;
				if((!stricmp(weapon,"QCRocketLauncher")                                     || !stricmp(weapon,"QCRocketLauncherDM")                                      ) && (CheckInventory("QCRocketAmmo") > 10)) break;
				if((!stricmp(weapon,"QCLightningGun")                                       || !stricmp(weapon,"QCLightningGunDM")                                        ) && (CheckInventory("QCCoilAmmo")   > 10)) break;
				if((!stricmp(weapon,"QCRailgun")                                            || !stricmp(weapon,"QCRailgunDM")                                             ) && (CheckInventory("QCSlugAmmo")   >  5)) break;
				if((!stricmp(weapon,"QCBFG")                                                || !stricmp(weapon,"QCBFGDM")                                                 ) && (CheckInventory("QCBFGAmmo")    >  0)) break;
				
				if((!stricmp(weapon,"QCMachinegun") || !stricmp(weapon,"QCHeavyMachinegun") || !stricmp(weapon,"QCMachinegunDM") || !stricmp(weapon,"QCHeavyMachinegunDM"))) if(CheckInventory("QCBulletAmmo")) noammo = false; else noammo = true;
				if((!stricmp(weapon,"QCShotgun")    || !stricmp(weapon,"QCSuperShotgun")    || !stricmp(weapon,"QCShotgunDM")    || !stricmp(weapon,"QCSuperShotgunDM")   )) if(CheckInventory("QCShellAmmo") ) noammo = false; else noammo = true;
				if((!stricmp(weapon,"QCNailgun")    || !stricmp(weapon,"QCSuperNailgun")    || !stricmp(weapon,"QCNailgunDM")    || !stricmp(weapon,"QCSuperNailgunDM")   )) if(CheckInventory("QCNailAmmo")  ) noammo = false; else noammo = true;
				if((!stricmp(weapon,"QCTribolt")                                            || !stricmp(weapon,"QCTriboltDM")                                             )) if(CheckInventory("QCBoltAmmo")  ) noammo = false; else noammo = true;
				if((!stricmp(weapon,"QCRocketLauncher")                                     || !stricmp(weapon,"QCRocketLauncherDM")                                      )) if(CheckInventory("QCRocketAmmo")) noammo = false; else noammo = true;
				if((!stricmp(weapon,"QCLightningGun")                                       || !stricmp(weapon,"QCLightningGunDM")                                        )) if(CheckInventory("QCCoilAmmo")  ) noammo = false; else noammo = true;
				if((!stricmp(weapon,"QCRailgun")                                            || !stricmp(weapon,"QCRailgunDM")                                             )) if(CheckInventory("QCSlugAmmo")  ) noammo = false; else noammo = true;
				if((!stricmp(weapon,"QCBFG")                                                || !stricmp(weapon,"QCBFGDM")                                                 )) if(CheckInventory("QCBFGAmmo")   ) noammo = false; else noammo = true;
				
			}
			///* debug */ log(s:"\c[bludi]Changed from ", s:weapon, s:" to ", s:GetWeapon());
		}
		else if
			(((CheckWeapon("QCMachinegun") || CheckWeapon("QCHeavyMachinegun") || CheckWeapon("QCMachinegunDM") || CheckWeapon("QCHeavyMachinegunDM")) && (CheckInventory("QCBulletAmmo") > 50)) ||
			 ((CheckWeapon("QCShotgun")    || CheckWeapon("QCSuperShotgun")    || CheckWeapon("QCShotgunDM")    || CheckWeapon("QCSuperShotgunDM")   ) && (CheckInventory("QCShellAmmo")  > 10)) ||
			 ((CheckWeapon("QCNailgun")    || CheckWeapon("QCSuperNailgun")    || CheckWeapon("QCNailgunDM")    || CheckWeapon("QCSuperNailgunDM")   ) && (CheckInventory("QCNailAmmo")   > 50)) ||
			 ((CheckWeapon("QCTribolt")                                        || CheckWeapon("QCTriboltDM")                                         ) && (CheckInventory("QCBoltAmmo")   > 10)) ||
			 ((CheckWeapon("QCRocketLauncher")                                 || CheckWeapon("QCRocketLauncherDM")                                  ) && (CheckInventory("QCRocketAmmo") > 10)) ||
			 ((CheckWeapon("QCLightningGun")                                   || CheckWeapon("QCLightningGunDM")                                    ) && (CheckInventory("QCCoilAmmo")   > 10)) ||
			 ((CheckWeapon("QCRailgun")                                        || CheckWeapon("QCRailgunDM")                                         ) && (CheckInventory("QCSlugAmmo")   >  5)) ||
			 ((CheckWeapon("QCBFG")                                            || CheckWeapon("QCBFGDM")                                             ) && (CheckInventory("QCBFGAmmo")    >  0)) ||
			 ((CheckWeapon("QCGauntlet")                                       || CheckWeapon("QCGauntletDM")                                        )))
			warned = 0;
		
		//* debug */ log(s:"Warning state = ", d:warned);
	}
}

script "QCDE_TrackLowHealth_CLIENT" (void) CLIENTSIDE
{
	if(PlayerNumber() - ConsolePlayerNumber()) terminate; // Only for myself
	
	bool warned;
	while(GetActorProperty(0, APROP_Health) > 0)
	{
		delay(3);
		
		// Console toggle
		if(!GetCvar("cl_lowHealthWarning"))
		{
			delay(70);
			continue;
		}
		
		// Health tracker
		int health = GetActorProperty(0, APROP_Health);
		if (health <= 30 && health > 0)
		{
			if(warned) continue;
			
			ACS_NamedExecuteAlways("QCDE_LowHealthAlert_CLIENT",0, true, GetCvar("cl_lowHealthWarning") > 1);
			warned = true;
			//* debug */ log(s:"\c[bludi]Alerting about low health! Text: ", d:GetCvar("cl_lowHealthWarning") > 1, s:", stays: ", d:GetCvar("cl_lowHealthWarning") >= 3);
			
			if(GetCvar("cl_lowHealthWarning") >= 3) 
			while(GetActorProperty(0, APROP_Health) <= 30)
			{
				delay(3);
				ACS_NamedExecuteAlways("QCDE_LowHealthAlert_CLIENT",0, false, true);
			}
		}
		else warned = false;
		
		//* debug */ log(s:"Warning state = ", d:warned);
	}
}

//=============================================================================
//
//		Footsteps
//
//=============================================================================
str FootstepType[NUMBER_OF_CLASSES + 1] = {
		"",						//0  Empty
		"QC/UI/MediumStep",		//1  Ranger
		"QC/UI/DoomStep",		//2  Doomslayer
		"QC/UI/ClothStep",		//3  Corvus
		"QC/UI/KaneStep",		//4  Kanerki
		"QC/UI/BootStep",		//5  Caleb
		"QC/UI/ClothStep",		//6  Menelkir
		"QC/UI/VisorStep",		//7  Terminator
		"QC/UI/HeavyStep",		//8  Zedek
		"QC/UI/RobotStep",		//9  Inquisitor
		"QC/UI/Q2Step",			//10 Bitterman
		"QC/UI/GalenStep",		//11 Galen
		"QC/UI/NyxStep",		//12 Nyx
		"QC/UI/SorgaulStep",	//13 Sorgaul
		"QC/UI/DukeNukemStep",	//14 DukeNukem
		"QC/UI/DurandalStep",	//15 Durandal
		"QC/UI/KeelStep",		//16 Keel
		"QC/UI/BootStep",		//17 Sarge
		"QC/UI/LoWangStep",		//18 LoWang
		"QC/UI/GraysonStep",	//19 Grayson
		"QC/UI/EradicatorStep",	//20 Eradicator
		"QC/UI/DukeNukemStep",	//21 Blazkowicz
		"QC/UI/FreemanStep",	//22 Freeman
		"QC/UI/VorMaturStep",	//23 VorMatur
		"QC/UI/EleenaStep",		//24 Eleena
		"QC/UI/NyxStep",		//25 Lucienne
		"QC/UI/MediumStep",		//26 Major
		"QC/UI/HunterStep",		//27 Hunter
		"QC/UI/DukeNukemStep",	//28 Sam
		"QC/UI/PostalStep",		//29 Postal
		"QC/UI/BootStep", 		//30 Painkiller
		"QC/UI/IntruderStep",   //31 Intruder
		// ^ insert more classes here
		}; 
int FootstepVol[NUMBER_OF_CLASSES + 1][2] = {
		{0,			},		//0  Empty
		{72,	10	},		//1  Ranger
		{72,	10	},		//2  Doomslayer
		{72,	10	},		//3  Corvus
		{72,	10	},		//4  Kanerki
		{60,	10	},		//5  Caleb
		{72,	10	},		//6  Menelkir 
		{96,	13	},		//7  Terminator
		{96,	13	},		//8  Zedek
		{96,	13	},		//9  Inquisitor
		{72,	12	},		//10 Bitterman
		{72,	10	},		//11 Galen
		{72,	 9	},		//12 Nyx
		{96,	11	},		//13 Sorgaul
		{80,	10	},		//14 DukeNukem
		{72,	10	},		//15 Durandal
		{88,	13	},		//16 Keel
		{70,	10	},		//17 Sarge
		{70,	10	},		//18 LoWang
		{50,	10	},		//19 Grayson, they're damn loud
		{96,	13	},		//20 Eradicator
		{80,	10	},		//21 Blazkowicz
		{80,	10	},		//22 Freeman
		{50,	13	},		//23 VorMatur
		{60,	10	},		//24 Eleena
		{72,	10	},		//25 Lucienne
		{72,	11	},		//26 Major
		{72,	10	},		//27 Hunter
		{72,	12	},		//28 Sam
		{72,	10	},		//29 Postal
		{72,	10	},		//30 Painkiller
		{84,	10	},		//31 Intruder
		// ^ insert more classes here
		}; 

function int floorcheck (void)	// function to check if player is in the floor
{								// which is later used for the footsteps
	int temp;
	temp = GetActorZ(0) - GetActorFloorZ(0);
	return temp;
}

function int speedcheck (void)	// to determine the speed, later used to 
{								// verify if footsteps should be played
	int x, y, speed, roundedspeed, maintimer;
	x = GetActorVelX(0);
	y = GetActorVelY(0);
	speed = FixedMul(x, x) + FixedMul(y, y);
	roundedspeed = sqrt(speed);
	return roundedspeed;
}

int playerSpeed;
script "Footstep_Initialize" (void)	// this one with the fuctions above determines if player
{									// is in the ground AND going fast enough to play footsteps
}


//=============================================================================
//
//		Rocket whoosh
//
//=============================================================================

// Activator: noisy projectile in flight
script "QCDE_AttachWhoosh" (void) CLIENTSIDE
{
	// remember rocket
	int tid = ActivatorTid();
	if(!tid)
	{
		tid = UniqueTid();
		Thing_ChangeTid(0,tid);
	}
	
	// don't whoosh if your own rocket
	SetActivatorToTarget(0);
	if(ConsolePlayerNumber() == PlayerNumber()) terminate;
	
	// whoosh!
	PlaySound(tid, "QC/Weapons/RocketLauncher/Fly",CHAN_5,0.5,true,1.0);
}





//=============================================================================
//
//		DPS testing
//
//=============================================================================

#define DPS_COOLDOWN 150
// Activator: actor with a lot of health
script "QCDE_AttachDPSTest" (void) 
{
	int hpWas, hp = GetActorProperty(0, APROP_HEALTH);
	int firsthp = hp;
	
	PrintBold(s:"\c[brite]DPS tester ready for abuse.\n\nShoot to start measurement.\nStop shooting for ", d:DPS_COOLDOWN, s:" tics to finish.");
	while(hp == GetActorProperty(0, APROP_HEALTH)) delay(1);
	
	int firsttime = Timer() - 1;
	int lasttime = Timer();
	int dmg, lastdmg, bestdmg;
	int duration,  dps;
	while(Timer() - lasttime < DPS_COOLDOWN)
	{
		hpWas = hp;
		hp = GetActorProperty(0, APROP_HEALTH);
		if(hpWas > hp) 
		{
			lastdmg = hpWas - hp;
			dmg += lastdmg;
			lasttime = Timer();
		}
		if(bestdmg < lastdmg) bestdmg = lastdmg;
		
		duration = Timer() - firsttime;
		dps = dmg * 0.25 / duration * 140;
		
		PrintBold(s:"Damage so far: ", d:dmg, s:"\nLast burst: ", d:lastdmg, s:"\nGreatest burst: ", d:bestdmg, s:"\n\nTics: ",d:Timer() - firsttime,s:"\n\n\c[brite]DPS so far:",f:dps);
		
		delay(1);
	}
	
	duration = lasttime - firsttime;
	dps = dmg * 0.25 / duration * 140;
	
	PrintBold(s:"\c[brite] : : :   Action Report   : : : \n\n Total damage: \c[bludi]", d:dmg, 
			s:"\n Greatest burst: \c[bludi]", d:bestdmg, 
			s:"\n Total time: \c[white]", d:lasttime - firsttime, 
			s:"\n\n DPS: \c[brite]", f:dps);
	
	Thing_Destroy(0);
}





//=============================================================================
//
//		Class usage stats
//
//=============================================================================

Script "QCDE_ClassUsageStats" OPEN
{
	delay(35 * 60);
	
	for(int i = 0; i < 64; i++)
	{
		if(!PlayerInGame(i)) continue;
		if( PlayerIsBot (i)) continue;
		
		str cvar = strparam(s:"_cu_", d:CheckActorInventory(1000+i,"ClassID"));
		SetCvar(cvar, GetCvar(cvar) + 1);
		
		delay(3);
		//log(n:i+1, s:" [", s:cvar, s:"] = ", d:GetCvar(cvar));
	}
	
	restart;
}

str classnames[NUMBER_OF_CLASSES] = {
"Ranger"    ,"Doomslayer","Corvus"    ,"Kane"      ,"Caleb"     ,
"Menelkir"  ,"Terminator","Zedek"     ,"Inquisitor","Bitterman" ,
"Galen"     ,"Nyx"       ,"Sorgaul"   ,"DukeNukem" ,"Durandal"  ,
"Keel"      ,"Sarge"     ,"LoWang"    ,"Grayson"   ,"Eradicator",
"Blazkowicz","Freeman"   ,"VorMatur"  ,"Eleena"    ,"Lucienne"  ,
"Major"     ,"Hunter"    ,"Sam"       ,"Postal"    ,"Painkiller",
"Intruder"  ,
};

Script "QCDE_ClassUsageDump" UNLOADING
{
	if(!GetCvar("_cu_log")) terminate;
	
	log(s:"All-time class usage in minutes:");
	
	for(int i = 0; i < NUMBER_OF_CLASSES; i++)
	{
		int value = GetCvar(strparam(s:"_cu_", d:i));
		log(s:"[", d:i/10, d:i%10, s:"] = ", d:value, s:" (", s:classnames[i], s:")");
	}
}
