#library "UTWEAPON"
#include "zcommon.acs"
#import "QCDE.bcs"

Script "UTDE_RlAltCheck" (void)
{
	if(GetPlayerInput(-1, INPUT_BUTTONS) & BT_ATTACK)
		SetResultValue(1);
	else
		SetResultValue(0);
}


// Activator: noisy projectile in flight
script "UTDE_AttachWhoosh" (void)
{
	// redeemer rocket
	int tid = ActivatorTid();
	if(!tid)
	{
		tid = UniqueTid();
		Thing_ChangeTid(0,tid);
	}

	// whoosh!
	PlaySound(tid, "UTDE/Weapons/Redeemer/Fly",CHAN_5,1.0,true,1.0);
}


script "UTDE_HoldBioNoAmmo" (void)
{
	if(CheckInventory("QCBoltAmmo") <= 0 && GetPlayerInput(-1, INPUT_BUTTONS) & BT_ALTATTACK)
		SetResultValue(1);
	else
		SetResultValue(0);
}

script "UTDE_HoldRocketNoAmmo" (void)
{
	if(CheckInventory("QCRocketAmmo") <= 0 && GetPlayerInput(-1, INPUT_BUTTONS) & BT_ALTATTACK)
		SetResultValue(1);
	else
		SetResultValue(0);
}

//----------------------------------------------------------------------
// Script for controlled redeemer rocket
#DEFINE SPEED    16
#DEFINE TURNSPEED 0.008
int greymask[64];

// Activator: controlled rocket
Script "UTDE_RedeemerControl" (void)
{
	int tid = GUIDEDROCK_TIDBASE + GetActorProperty(0, APROP_TargetTID) - 1000;
	int plrtid = GetActorProperty(0, APROP_TargetTID);
	int plr = plrtid - 1000;
	//printbold(s:"rocket flying with tid ", d:tid, s:", from ", n:plr + 1);

	Thing_ChangeTID(0, tid);

	SetActivator(plrtid);
	// Activator: rocket owner

	delay(1);

	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	ChangeCamera(tid, false, false);
	SetNetworkReplicationFlags( 0 );
	SetActivator(tid);
	// Activator: controlled rocket

	greymask[plr] = true;
	int origa = GetActorAngle(plrtid), a = origa;
	int origp = GetActorPitch(plrtid), p = origp;
	while(!CheckInventory("ImDead") && GetActorProperty(tid, APROP_Health) > 0)
	{
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );

		Thing_Stop(tid);

		int ip = -GetPlayerInput(plr, INPUT_PITCH);
		if(ip >  TURNSPEED) ip =  TURNSPEED;
		if(ip < -TURNSPEED) ip = -TURNSPEED;
		p += ip;
		if(p >  0.25) p =  0.25;
		if(p < -0.25) p = -0.25;

		int spd_ver = (-sin(p) * SPEED) >> 14;
		ThrustThingZ(tid, spd_ver, 0, 0);

		int ia = GetPlayerInput(plr, INPUT_YAW);
		if(ia >  TURNSPEED) ia =  TURNSPEED;
		if(ia < -TURNSPEED) ia = -TURNSPEED;
		a += ia;

		int spd_hor = (cos(p) * SPEED) >> 16;
		ThrustThing(a>>8, spd_hor, 1, tid);
		SetActorAngle(tid, a);
		SetActorPitch(tid, p);

		SetNetworkReplicationFlags( 0 );

		delay(1);

		int triggers = GetPlayerInput(plr, INPUT_BUTTONS) & ~GetPlayerInput(plr, INPUT_OLDBUTTONS);
		if(triggers & (BT_ATTACK | BT_ALTATTACK))
			GiveInventory("ImDead",1);
	}
	greymask[plr] = false;
	while(IsTidUsed(tid))
	{
		delay(1);
	}
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	SetActorAngle(plrtid, origa);
	SetActorPitch(plrtid, origP);
	SetNetworkReplicationFlags( 0 );

	SetActivator(plrtid);
	SetPlayerProperty(0,0,PROP_TOTALLYFROZEN);
}

//this is the dark screen effect, will loop until the projectile terminates it manually
Script "UTDE_TunnelVision" (void)
{
	if (GetNetworkState() == NETSTATE_SERVER)
		terminate;

	delay(2); // time for rocket to initialize
	int plrtid = GetActorProperty(0, APROP_TargetTID);
	int plr = plrtid - 1000;
	SetActivator(plrtid);
	SetHudSize(320,240,1);
	SetFont("REDEEMER");
	while(greymask[plr])
	{
		//Log(s:"aaa");
		HudMessage(s:"A"; HUDMSG_PLAIN, HMID_TUNNEL_VISION + 63, -1, 160.0, 120.0, 0.1);
		delay(2);
	}
}
