#library "WEAPONS"
#include "zcommon.acs"
#include "AACS.acs"
#import "QCDE.bcs"
#import "WEAPCNST.bcs"
#include "../BotSource/headers/TDBots.h.bcs"

Script "QCDE_GetWeaponsType" (void)
{
	SetResultValue("Unreal");
}

int weaponSpawned[NUMBER_OF_WEAPONS];

Script "QCDE_WeaponSpawned" (int type, int arg4)
{
	// Weapon-centric modes
	if(GetCvar("instagib") || GetCvar("rocketarena"))
	{
		//log(s:"Weapon removed: ", s:weaponList[type]);
		Thing_Remove(0);
		terminate;
	}

	if(arg4 == 234)
	{
		//log(s:"Weapon spawns its smoke: ", s:weaponList[type]);
		str smonk = "WeaponSpawnPointBase";
		switch(type)
		{
		case  8: smonk = "SpawnPoint_HMG"; break;
		case 10: smonk = "SpawnPoint_SSG"; break;
		case 12: smonk = "SpawnPoint_SNG"; break;
		case 14: smonk = "SpawnPoint_TB" ; break;
		case 16: smonk = "SpawnPoint_RL" ; break;
		case 18: smonk = "SpawnPoint_LG" ; break;
		case 20: smonk = "SpawnPoint_RG" ; break;
		case 22: smonk = "SpawnPoint_BFG"; break;
		case 3: case 7: case 9: case 11: case 13: case 15: case 17: case 19: case 21: smonk = "FX"; break;
		default: log(s:"QCDE Warning: Unexpected weapon type spawning smoke: ", d:type); break;
		}

		int x = GetActorX(0);
		int y = GetActorY(0);
		int z = GetActorZ(0);
		SpawnForced(smonk, x,y,z);
	}

	//log(s:"Weapon trying to spawn: ", s:weaponList[type]);

	SetTidIfHadNone(WEAPON_TIDBASE, WEAPON_TIDLAST);

	weaponSpawned[type] = true;
	//log(s:"Weapon ", d:type, s:" spawns successfully ", s:weaponList[type], s:", tid = ", d:tid);
}

Script "QCDE_IsWeaponOnMap" (int type)
{
	if(type >= 0 && type < NUMBER_OF_WEAPONS)
		SetResultValue(weaponSpawned[type]);
	else
		log(s:"QCDE WARNING: Weapon ", d:type, s:" is queried. Timer: ", d:Timer());
}

// Activator: weapon pickup
Script "QCDE_SetWeaponRespawnTics" (void)
{
	int result;
	if (!GetCvar("sv_itemrespawn"))
		result = 0x7FFFFFFF;
	else if (GetCvar("sv_weaponrespawn"))
		result = (GetCvar("sv_weaponrespawn") - 1) * 35; // + 1 second from Decorate
	else if(GetCvar("duel"))
		result = 4 * 35; // + 1 second from Decorate
	else // all non-duel games with items set to respawn
		result = 0 * 35; // + 1 second from Decorate
	//PrintBold(n:0, s:" result: ", d:result);
	SetResultValue(result);
}


//=============================================================================
//
//		Rocket whoosh
//
//=============================================================================

// Activator: noisy projectile in flight
script "QCDE_AttachWhoosh" (void) CLIENTSIDE
{
	// remember rocket
	int tid = ActivatorTid();
	if(!tid)
	{
		tid = UniqueTid();
		Thing_ChangeTid(0,tid);
	}

	// don't whoosh if your own rocket
	SetActivatorToTarget(0);
	if(ConsolePlayerNumber() == PlayerNumber()) terminate;

	// if rocket isn't moving, then it has exploded already. So no whoosh
	if (GetActorVelX(tid) || GetActorVelY(tid) || GetActorVelZ(tid))
		PlaySound(tid, "QC/Weapons/RocketLauncher/Fly",CHAN_5,0.5,true,1.0); // whoosh!
}


// Activator: noisy projectile in flight
script "UTDE_AttachWhooshShock" (void)
{
	// redeemer rocket
	int tid = ActivatorTid();
	if(!tid)
	{
		tid = UniqueTid();
		Thing_ChangeTid(0,tid);
	}

	// if orb isn't moving, then it has exploded already. So no whoosh
	if (GetActorVelX(tid) || GetActorVelY(tid) || GetActorVelZ(tid))
		PlaySound(tid, "UTDE/Weapons/ShockRifle/OrbFly",CHAN_5,1.0,true,1.0); // whoosh!
}

// Activator: noisy projectile in flight
script "UTDE_AttachWhooshRedeemer" (void)
{
	// redeemer rocket
	int tid = ActivatorTid();
	if(!tid)
	{
		tid = UniqueTid();
		Thing_ChangeTid(0,tid);
	}

	// if rocket isn't moving, then it has exploded already. So no whoosh
	if (GetActorVelX(tid) || GetActorVelY(tid) || GetActorVelZ(tid))
		PlaySound(tid, "UTDE/Weapons/Redeemer/Fly",CHAN_5,1.0,true,1.0); // whoosh!
}


//----------------------------------------------------------------------
// Script for controlled redeemer rocket
#DEFINE SPEED    16
#DEFINE TURNSPEED_BASE 0.008
#DEFINE TURNSPEED_UPGRADED 0.015
int greymask[64];

// Activator: controlled rocket
Script "QCDE_RocketControl" (void)
{
	int tid = GUIDEDROCK_TIDBASE + GetActorProperty(0, APROP_TargetTID) - 1000;
	int plrtid = GetActorProperty(0, APROP_TargetTID);
	int plr = plrtid - 1000;
	//printbold(s:"rocket flying with tid ", d:tid, s:", from ", n:plr + 1);

	Thing_ChangeTID(0, tid);

	SetActivator(plrtid);
	// Activator: rocket owner

	int turnSpeed = TURNSPEED_BASE;
	if (CheckInventory("BFG_UG_Charge"))
		turnSpeed = TURNSPEED_UPGRADED;

	delay(1);

	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	ChangeCamera(tid, false, false);
	SetNetworkReplicationFlags( 0 );
	SetActivator(tid);
	// Activator: controlled rocket

	greymask[plr] = true;
	int origa = GetActorAngle(plrtid), a = origa;
	int origp = GetActorPitch(plrtid), p = origp;
	while(!CheckInventory("ImDead") && GetActorProperty(tid, APROP_Health) > 0)
	{
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );

		Thing_Stop(tid);

		int ip = -GetPlayerInput(plr, INPUT_PITCH);
		if(ip >  turnSpeed) ip =  turnSpeed;
		if(ip < -turnSpeed) ip = -turnSpeed;
		p += ip;
		if(p >  0.25) p =  0.25;
		if(p < -0.25) p = -0.25;

		int spd_ver = (-sin(p) * SPEED) >> 14;
		ThrustThingZ(tid, spd_ver, 0, 0);

		int ia = GetPlayerInput(plr, INPUT_YAW);
		if(ia >  turnSpeed) ia =  turnSpeed;
		if(ia < -turnSpeed) ia = -turnSpeed;
		a += ia;

		int spd_hor = (cos(p) * SPEED) >> 16;
		ThrustThing(a>>8, spd_hor, 1, tid);
		SetActorAngle(tid, a);
		SetActorPitch(tid, p);

		SetNetworkReplicationFlags( 0 );

		delay(1);

		int triggers = GetPlayerInput(plr, INPUT_BUTTONS) & ~GetPlayerInput(plr, INPUT_OLDBUTTONS);
		if(triggers & (BT_ATTACK | BT_ALTATTACK))
			GiveInventory("ImDead",1);
	}
	greymask[plr] = false;
	while(IsTidUsed(tid))
	{
		delay(1);
	}
	SetNetworkReplicationFlags( NETREP_SKIPOWNER );
	SetActorAngle(plrtid, origa);
	SetActorPitch(plrtid, origP);
	SetNetworkReplicationFlags( 0 );

	SetActivator(plrtid);
	SetPlayerProperty(0,0,PROP_TOTALLYFROZEN);
}

//this is the dark screen effect, will loop until the projectile terminates it manually
Script "QCDE_TunnelVision" (void)
{
	if (GetNetworkState() == NETSTATE_SERVER)
		terminate;

	delay(2); // time for rocket to initialize
	int plrtid = GetActorProperty(0, APROP_TargetTID);
	int plr = plrtid - 1000;
	SetActivator(plrtid);
	SetHudSize(320,240,1);
	SetFont("REDEEMER");
	while(greymask[plr])
	{
		//Log(s:"aaa");
		HudMessage(s:"A"; HUDMSG_PLAIN, HMID_TUNNEL_VISION + 63, -1, 160.0, 120.0, 0.1);
		delay(2);
	}
}

Script "QCDE_ResetRocketFov" (void)
{
	int tid = GUIDEDROCK_TIDBASE + GetActorProperty(0, APROP_TargetTID) - 1000;
	SetCameraToTexture(tid, "CAMERT", 90);
}


//------------------------------------------------
// Weapon alt fire modifier messages

script "QCDE_ModSelectedText" (int weapon, int upgrade)
{
	//SetHUDSize(800,600,1);
	SetHUDSize(400,300,1);
	SetFont("ESFONTAA");
	str color = strparam(s:"\c[", s:GetWeapon(), s:"]");
	HudMessage(s:color, s:WeaponUpgrades[weapon][1][WU_PROPERNAME], s:" engaged";HUDMSG_PLAIN,101,-1,200.0,240.0,0);

	while(checkinventory("WeaponZoomedToken"))
	{
		Delay(2);
	}

	ACS_NamedExecuteAlways("RemoveModText",0,0);
}

script "RemoveModText" (void)
{
	HudMessage(s:" ";HUDMSG_PLAIN,101,"SkyBlue",0.75,1.0,0.1);
}


//------------------------------------------------
// Weapon hitmarker

script "QCDE_HitMark" (void) clientside
{
	if(IsZandronum(true))
		if(ActivatorTid() != CheckPlayerCamera(ConsolePlayerNumber()))
			terminate;

	SetHUDSize(1200,900,1);
	SetFont("HITMED");
	HudMessageBold(s:"a";HUDMSG_FADEOUT,-234,-1,600.0,450.0,0.0,0.15);
}

Script "QCDE_ConfigureBotWeapons" (void)
{
	// Define ability weapons with max priority and infinite range, to prevent bots from switching to other weapons
 	TDB_Weapon_New(		"BlazkoAkimboBot",		10);
 	TDB_Weapon_New(		"CalebDollBot",			10);
 	TDB_Weapon_New(		"SlayerBFG",			10);
 	TDB_Weapon_New(		"Shieldquisitor",		10);
 	TDB_Weapon_New(		"PostalCowHead",		10);
 	TDB_Weapon_New(		"SorgaulFistsBot",		10);

 	// Setup fire modes
 	//					Name					Ammo Class		Ammo Use	Proj Speed	Min Dist	Max Dist	Flags								Alt Fire chance
 	TDB_Weapon_Pri(		"BlazkoAkimboBot",		"",					0,		25.0,		0.0,		MAX_RANGE,	TDB_CW_PROJECTILE);
 	TDB_Weapon_Alt(		"BlazkoAkimboBot",		"",					0,		0.0,		0.0,		MAX_RANGE,	0,									0.5);
 	TDB_Weapon_Pri(		"CalebDollBot",			"",					0,		0.0,		0.0,		MAX_RANGE,	TDB_CW_MELEE); // Using melee so that Caleb tried to get closer
 	TDB_Weapon_Pri(		"SlayerBFG",			"",					0,		25.0,		0.0,		MAX_RANGE,	TDB_CW_PROJECTILE);
 	TDB_Weapon_Pri(		"Shieldquisitor",		"",					0,		0.0,		0.0,		MAX_RANGE,	0);
 	TDB_Weapon_Pri(		"PostalCowHead",		"",					0,		14.0,		0.0,		MAX_RANGE,	TDB_CW_PROJECTILE);
 	TDB_Weapon_Pri(		"SorgaulFistsBot",		"",					0,		0.0,		0.0,		MAX_RANGE,	TDB_CW_MELEE);

	// Define normal weapons
	//					Name				Priority
	TDB_Weapon_New(		"DukeFreezeThrower",	4);
	TDB_Weapon_New(		"SamMinigun",			3);
	TDB_Weapon_New(		"QCGauntlet",			0);
	TDB_Weapon_New(		"QCMachinegunDM",		1);
	TDB_Weapon_New(		"QCHeavyMachinegunDM",	2);
	TDB_Weapon_New(		"QCShotgunDM",			1);
	TDB_Weapon_New(		"QCSuperShotgunDM",		2);
	TDB_Weapon_New(		"QCNailgunDM",			1);
	TDB_Weapon_New(		"QCSuperNailgunDM",		2);
	TDB_Weapon_New(		"QCTriboltDM",			2);
	TDB_Weapon_New(		"QCRocketLauncherDM",	3);
	TDB_Weapon_New(		"QCLightningGunDM",		3);
	TDB_Weapon_New(		"QCRailgunDM",			3);
	TDB_Weapon_New(		"QCBFGDM",				4);

	// Setup fire modes
	//					Name					Ammo Class		Ammo Use	Proj Speed	Min Dist	Max Dist	Flags								Alt Fire chance
	// Abilities
	TDB_Weapon_Pri(		"DukeFreezeThrower",	"DukeAmmo",			1,		25.0,		0.0,		400.0,		TDB_CW_PROJECTILE);
	TDB_Weapon_Pri(		"SamMinigun",			"SeriousBullets",	1,		0.0,		0.0,		700.0,		0);
	TDB_Weapon_Alt(		"SamMinigun",			"SeriousBullets",	1,		0.0,		0.0,		400.0,		0,									0.5);

	//					Name					Ammo Class		Ammo Use	Proj Speed	Min Dist	Max Dist	Flags	Alt Fire chance
	// Starter weapons + upgrades
	TDB_Weapon_Pri(		"QCGauntlet",			"",					0,		0.0,		0.0,		55.0,		TDB_CW_MELEE);
	TDB_Weapon_Pri(		"QCMachinegunDM",		"QCBulletAmmo",		1,		0.0,		200.0,		MAX_RANGE,	0);
	TDB_Weapon_Pri(		"QCHeavyMachinegunDM",	"QCBulletAmmo",		1,		0.0,		200.0,		MAX_RANGE,	0);
	TDB_Weapon_Alt(		"QCHeavyMachinegunDM",	"QCBulletAmmo",		1,		0.0,		0.0,		400.0,		0,									0.5);
	TDB_Weapon_Pri(		"QCShotgunDM",			"QCShellAmmo",		1,		0.0,		0.0,		200.0,		0);
	TDB_Weapon_Pri(		"QCSuperShotgunDM",		"QCShellAmmo",		1,		65.0,		0.0,		200.0,		TDB_CW_PROJECTILE);
	TDB_Weapon_Alt(		"QCSuperShotgunDM",		"QCShellAmmo",		1,		25.0,		200.0,		500.0,		TDB_CW_PROJECTILE|TDB_CW_EXPLOSIVE,	0.5);
	TDB_Weapon_Pri(		"QCNailgunDM",			"QCNailAmmo",		1,		52.0,		0.0,		250.0,		TDB_CW_PROJECTILE);
	TDB_Weapon_Pri(		"QCSuperNailgunDM",		"QCNailAmmo",		1,		52.0,		0.0,		250.0,		TDB_CW_PROJECTILE);
	TDB_Weapon_Alt(		"QCSuperNailgunDM",		"QCNailAmmo",		1,		0.0,		250.0,		700.0,		0,									0.5);

	//					Name					Ammo Class		Ammo Use	Proj Speed	Min Dist	Max Dist	Flags	Alt Fire chance
	// Strong weapons
	TDB_Weapon_Pri(		"QCTriboltDM",			"QCBoltAmmo",		1,		30.0,		0.0,		400.0,		TDB_CW_PROJECTILE);
	TDB_Weapon_Pri(		"QCRocketLauncherDM",	"QCRocketAmmo",		1,		34.0,		0.0,		400.0,		TDB_CW_PROJECTILE|TDB_CW_EXPLOSIVE);
	TDB_Weapon_Pri(		"QCLightningGunDM",		"QCCoilAmmo",		1,		0.0,		200.0,		MAX_RANGE,	0);
	//TDB_Weapon_Alt(		"QCLightningGunDM",		"QCCoilAmmo",		2,		18.0,		200.0,		700.0,		TDB_CW_PROJECTILE,									0.5);
	TDB_Weapon_Pri(		"QCRailgunDM",			"QCSlugAmmo",		1,		0.0,		600.0,		MAX_RANGE,	0);
	TDB_Weapon_Pri(		"QCBFGDM",				"QCBFGAmmo",		1,		45.0,		0.0,		700.0,		TDB_CW_PROJECTILE|TDB_CW_EXPLOSIVE);
}


// Freeman PvE Ammo Box passive. Placing the script here for weapon addons to override
// Activator: dying victim
Script "QCDE_MonsterKill_QCFreeman" (void)
{
	if(CheckInventory("MonsterBig") || CheckInventory("MonsterBoss"))
	{
		int itemAmount = 0;
		itemAmount |= (random(0, 5) & 0xFF); // Sniper
		itemAmount <<= 8;
		itemAmount |= (random(0, 6) & 0xFF); // Rocket Launcher
		itemAmount <<= 8;
		itemAmount |= (random(0, 30) & 0xFF); // Pulse Gun
		itemAmount <<= 8;
		itemAmount |= (random(0, 30) & 0xFF); // Minigun

		if (itemAmount > 0)
			DropItem(0, "FreemanWeaponBox1", itemAmount, 256);

		itemAmount = 0;
		itemAmount |= (random(0, 1) & 0xFF); // Redeemer
		itemAmount <<= 8;
		itemAmount |= (random(0, 15) & 0xFF); // Shock Rifle
		itemAmount <<= 8;
		itemAmount |= (random(0, 20) & 0xFF); // Ripper
		itemAmount <<= 8;
		itemAmount |= (random(0, 10) & 0xFF); // Flak Cannon

		if (itemAmount > 0)
			DropItem(0, "FreemanWeaponBox2", itemAmount, 256);
	}
}

//------------------------------------------------
// Give Tribolt on map03
// or after 30 minutes on one map

Script "QCDE_MapsPlayed" OPEN
{
	GiveActorInventory(0,"MapsPlayed",1);
}

Script "QCDE_FreeTribolt" (void)
{
	if(GameType() >= GAME_NET_DEATHMATCH) terminate;
	if(CheckInventory("QCTribolt")) terminate;

	if(CheckInventory("MapsPlayed") != 2 + (GameType() == GAME_SINGLE_PLAYER))
		delay(30 * 60 * 35);

	SpawnForced("QCTribolt", GetActorX(0),GetActorY(0),GetActorZ(0));
}

Script "QCDE_ZoomControl" (int predicting, int justPressed, int justReleased, int buttons)
{
	if (!predicting)
	{
		// in UTDE, only Sniper  Rifle can zoom
		if (CheckWeapon("QCRailgun") || CheckWeapon("QCRailgunDM"))
		{
			bool shouldZoomIn = !CheckInventory("WeaponZoomedToken") && justPressed;
			bool shouldZoomOut = CheckInventory("WeaponZoomedToken") && GetCVar("cl_holdZoom") ? justReleased : justPressed;

			if (shouldZoomIn)
			{
				SetNetworkReplicationFlags( NETREP_SKIPOWNER );
				PlaySound(0,"UTDE/Weapons/SniperRifle/ZoomIn",CHAN_7,1.0,false);
				SetNetworkReplicationFlags( 0 );
				SetInventory("WeaponZoomedToken", 1);
				SetPlayerWeaponZoomFactor(PlayerNumber(), GetCVar("cl_sniperZoom"));
			}
			else if (shouldZoomOut)
			{
				SetNetworkReplicationFlags( NETREP_SKIPOWNER );
				PlaySound(0,"UTDE/Weapons/SniperRifle/ZoomOut",CHAN_7,1.0,false);
				SetNetworkReplicationFlags( 0 );
				SetInventory("WeaponZoomedToken", 0);
				SetPlayerWeaponZoomFactor(PlayerNumber(), 1.0);
			}
		}
	}
}

Script "UTDE_RlAltCheck" (void)
{
	if(GetPlayerInput(-1, INPUT_BUTTONS) & BT_ATTACK)
		SetResultValue(1);
	else
		SetResultValue(0);
}



script "UTDE_HoldBioNoAmmo" (void)
{
	if(GetPlayerInput(-1, INPUT_BUTTONS) & BT_ALTATTACK)
		SetResultValue(1);
	else
		SetResultValue(0);
}

#define MOVEMENT_BUTTONS (BT_MOVELEFT|BT_FORWARD|BT_MOVERIGHT|BT_BACK)
script "UTDE_StationarySniperUpgrade" (void)
{
	// This passive is human-scum-only.
	if(PlayerIsBot(PlayerNumber())) terminate;

	while(strcmp(GetWeapon(),"QCRailgun") == 0)
	{
		SetNetworkReplicationFlags( NETREP_SKIPOWNER );
		bool takeCharges = GetPlayerInput(-1, INPUT_BUTTONS) & MOVEMENT_BUTTONS || !CheckInventory("WeaponZoomedToken");
		bool giveCharges = !takeCharges && CheckInventory("RG_UG_Explosive") && CheckInventory("RailgunCharges") < 52;
		if (takeCharges)
		{
			TakeInventory("RailgunCharges",32767);
		}
		else if (giveCharges)
		{
			GiveInventory("RailgunCharges",1);
			if (CheckInventory("RailgunCharges") >= 52)
			{
				PlaySound(0,"QC/Weapons/Railgun/ChargeFull",CHAN_6,1.0,false);
			}
		}
		SetNetworkReplicationFlags( 0 );

		delay(1);
	}
}